# Generated by Django 4.1.3 on 2022-11-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
